### PR TITLE
Fix jagged parentheses

### LINKED ISSUE #2198: 3x3 matrices render with jagged delimiters when used with pmatrix
While rendering a 3x3 matrix, a part of the delimiters appear to be protruding. This nit picky detail is an issue when the matrix is viewed on a huge screen in front of a huge audience.
3x3

**LaTeX code:**
```latex
\begin{pmatrix}
    a & b & c\\
    a & b & c\\
    a & b & c\\
\end{pmatrix}
```

**Expected behavior:**
Did a quick render of the same Latex code using [QuickLaTeX](https://www.quicklatex.com/) to generate this image:
3x3_right

**Environment:**
 - KaTeX Version: Version used in https://katex.org/ website's "Type an expression" editor
 - Device: Desktop
 - OS: Ubuntu 18.04
 - Browser: Google Chrome 80.0.3987.87

**Additional context:**
Originally, I noticed this issue in Joplin, a markdown text editor supporting Katex in it. To verify if the issue was in Joplin or the Katex engine, I used the "Type an expression" feature at https://katex.org/ to render a test image and found the issue.

### PR DESCRIPTION
**Pull request by ronkok**
Fixes #2198. 

As you may recall, an earlier issue (#1975) complained of occasional gaps in built-up vertical delimiters. PR #1986 introduced small overlaps at each junction, then added one extra repeat element to cover the last gap. For parentheses around a 3x3 matrix, that extra repeat element runs past the curve in the parenthesis and looks jagged.

This PR uses a shorter repeat element to cover that last gap.

### CODE REVIEW

File: src/delimiter.js [hunk 1]
```diff
@@ -375,9 +375,19 @@ const makeStackedDelim = function(
 
     // To cover the gap create by the overlaps, insert one more repeat element,
     // at a position that juts 0.005 above the bottom of the top element.
-    inners.push({type: "kern", size: shiftOfExtraElement});
-    inners.push(makeInner(repeat, font, mode));
-    inners.push(lap);
+    if ((repeat === "\u239c" || repeat === "\u239f") && repeatCount === 0) {
```
Comment (edemaine) [inline src/delimiter.js:378]: Why are parentheses special here? It seems like it would be a good idea to use a small connector whenever `repeatCount === 0`.

Perhaps there are some symbols where a vertical line segment isn't the right choice, but I feel like this might still be a better choice than the `else` case... Or at least perhaps we should do a little analysis of all the delimiters to decide?

File: src/delimiter.js [hunk 2]
```diff
@@ -375,9 +375,19 @@ const makeStackedDelim = function(
...
+        // Parentheses need a short repeat element in order to avoid an overrun.
+        // We'll make a 0.3em tall element from a SVG.
+        inners.push({type: "kern", size: -0.15});
```
Comment (edemaine) [inline src/delimiter.js:381]: Why 0.3em? It seems like the existing code uses 0.005em for the overlap shift, so I would have imagined using an 0.01em tall SVG with negative vertical shifts of 0.005em on either side.

Also, it would seem nicer to use the 0.3 (or whatever) constant in `svgdata.leftParenInner[2]` instead of repeating it here.

File: src/delimiter.js (hunk 1 above)
Comment (ronkok) [reply src/delimiter.js:378]: I don't get to pick any arbitrary small connector. If I don't use an SVG, then I am limited to font glyphs. And the selection of font glyphs is not ideal. The short ones were too thick, or had the wrong xMin distance or the wrong advance distance. After trying some alternative glyphs that made sense, none of them worked. I gave up and went the SVG route. It's a sure thing.

File: src/delimiter.js (hunk 2 above)
Comment (ronkok) [reply src/delimiter.js:381]: > Why 0.3em?

It's been awhile and I'm not 100% positive I remember this correctly, but I think 0.03em has a pretty big tolerance for adjustment. Since the SVG is used only in this one case where parens barely touch, it could be significantly bigger or smaller and still work.

I opted for the number at the bigger end of the range partly because I think I got the original 0.005em number wrong. I've seen some cases on my own screen where there is still a gap. I did not want to go too small a second time.

File: src/delimiter.js (hunk 1 above)
Comment (edemaine) [reply src/delimiter.js:378]: Yes, that makes sense. I was wondering why we're fixing the case of parentheses but not fixing the case of e.g. curly braces (which use `\u23aa` for their `repeat` character). Would bad things happen if we replaced this `if` statement with
```js
 if (repeatCount === 0) {
```
?

File: src/delimiter.js (hunk 2 above)
Comment (edemaine) [reply src/delimiter.js:381]: OK, and sounds safe enough in this case, but then maybe we should adjust the 0.005em number? (Can be in a separate PR effort.)

Do you agree with changing the `0.3` constant with `svgdata.leftParenInner[2]`?

Comment (ronkok) [reply src/delimiter.js:381]: > Also, it would seem nicer to use the 0.3 (or whatever) constant in svgdata.leftParenInner[2] instead of repeating it here.

Well, I certainly would do something of that nature if the SVG had multiple use cases. We have some other paths in `svgGeometry.js` that can grow or shrink, and we could have done that. But since this does get used for only one case, I thought that the constant number `0.3em` was easy to read.

I don't feel strongly about this one.

File: src/delimiter.js (hunk 1 above)
Comment (ronkok) [reply src/delimiter.js:378]: Curly braces have a longer straight section built into the glyph. I checked, and they do not need a correction similar to this PR. The existing short glyph remains hidden within the curly brace glyph.

File: src/delimiter.js (hunk 2 above)
Comment (ronkok) [reply src/delimiter.js:381]: Oops, I misunderstood your comment. You were tying this constant to a piece of data from `src/buildCommon.js`, not `svgGeometry.`. Sure. I have no problem with that. I'll make a change.

Comment (ronkok) [reply src/delimiter.js:381]: You've got quicker fingers that I do. You have approved this PR. Do you still want me to change the 0.3 constant?

Comment (edemaine) [reply src/delimiter.js:381]: Sure, now that we agree, please go ahead. I'll merge after checking the commit.

File: src/delimiter.js [hunk 3]
```diff
@@ -378,11 +378,12 @@ const makeStackedDelim = function(
     if ((repeat === "\u239c" || repeat === "\u239f") && repeatCount === 0) {
         // Parentheses need a short repeat element in order to avoid an overrun.
         // We'll make a 0.3em tall element from a SVG.
-        inners.push({type: "kern", size: -0.15});
+        const overlap = buildCommon.svgData.leftParenInner[2] / 2
```
Comment (edemaine) [inline src/delimiter.js]: This needs a semicolon (for lint).

**Comment by ronkok** [comment]
Thank you for the review!
