### PR TITLE
Prevent gaps in tall delimiters

### LINKED ISSUE #1975: Break in tall delimiters
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Left and right floor brackets, when containing a large expression, appear to to break in the middle. This disappears on zooming but makes for suboptimal rendering.

**(La)TeX code:**
```latex
5 = \left\lfloor{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{(4!)!}}}}}}\right\rfloor
```

**Expected behavior:**
Expected vertical bar portion of left and right floor braces to be continuous.

**Screenshots:**
Taken from [the demo](https://katex.org).
image

**Environment (please complete the following information):**
 - KaTeX Version: 0.10.1
 - Device: Desktop
 - OS: Ubuntu 18.10
 - Browser: Chrome
 - Version: 74.0.3729.131 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ronkok**
Fixes #1975 by typesetting tall delimiters with a small (0.005em) overlap where glyphs meet.

As evidence, I offer two screenshots. The first one is before this PR:
gap

The second screenshot is after this PR:
nogap

The value of 0.005em is entirely a guess on my part and may need later adjustment.

### CODE REVIEW

**Comment by ronkok** [comment]
@kevinbarabash This PR does several vertical alignment calculations and the screenshotter tests declare several errors. It appears to me that all of them are sub-pixel issues except the Array test, in which the diff shows one thin green line.

I'm willing to declare this PR as good to go, but I'll leave the screenshotter tests as is for now. If you agree that the PR is okay, I'll replace the screenshots with new ones.

**Comment by ronkok** [comment]
I went ahead and updated the screenshots.

File: src/delimiter.js [hunk 1]
```diff
@@ -339,20 +351,34 @@ const makeStackedDelim = function(
...
+            inners.push(lap);
             inners.push(makeInner(repeat, font, mode));
         }
     }
 
+    // To cover the gap create by the overlaps, insert one more repeat element,
+    // at a position that juts 0.005 above the bottom of the top element.
+    inners.push({type: "kern", size: shiftOfExtraElement});
+    inners.push(makeInner(repeat, font, mode));
+    inners.push(lap);
```
Comment (kevinbarabash) [inline src/delimiter.js]: ~In the `else` branch we do the same thing.  Do we need to insert two extra repeat elements?~ I see, there's two `for` loops in the `else` block.
